version: '2.3'
services:
  registry:
    image: goharbor/registry-photon:v2.1.4
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: /mnt/harbor/data/secret/registry/root.crt
        target: /etc/registry/root.crt
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - harbor-clair
  registryctl:
    image: goharbor/harbor-registryctl:v2.1.4
    container_name: registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/registry:/storage:z
      - ./common/config/registry/:/etc/registry/:z
      - type: bind
        source: ./common/config/registryctl/config.yml
        target: /etc/registryctl/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
  postgresql:
    image: goharbor/harbor-db:v2.1.4
    container_name: harbor-db
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/database:/var/lib/postgresql/data:z
    networks:
      harbor:
      harbor-notary:
        aliases:
          - harbor-db
      harbor-clair:
        aliases:
          - harbor-db
    env_file:
      - ./common/config/db/env
  core:
    image: goharbor/harbor-core:v2.1.4
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/ca_download/:/etc/core/ca/:z
      - /mnt/harbor/data/:/data/:z
      - ./common/config/core/certificates/:/etc/core/certificates/:z
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: /mnt/harbor/data/secret/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: /mnt/harbor/data/secret/keys/secretkey
        target: /etc/core/key
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      harbor:
      harbor-notary:
      harbor-clair:
        aliases:
          - harbor-core
      harbor-chartmuseum:
        aliases:
          - harbor-core
    depends_on:
      - registry
      - redis
      - postgresql
  portal:
    image: goharbor/harbor-portal:v2.1.4
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - type: bind
        source: ./common/config/portal/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - harbor
  jobservice:
    image: goharbor/harbor-jobservice:v2.1.4
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/job_logs:/var/log/jobs:z
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - harbor-clair
    depends_on:
      - core
  redis:
    image: goharbor/redis-photon:v2.1.4
    container_name: redis
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    volumes:
      - /mnt/harbor/data/redis:/var/lib/redis
    networks:
      harbor:
      harbor-chartmuseum:
        aliases:
          - redis
      harbor-clair:
        aliases:
          - redis
  proxy:
    image: goharbor/nginx-photon:v2.1.4
    container_name: nginx
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./common/config/nginx:/etc/nginx:z
      - /mnt/harbor/data/secret/cert:/etc/cert:z
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    networks:
      - harbor
      - harbor-notary
    ports:
      - 80:8080
      - 443:8443
      - 4443:4443
    depends_on:
      - registry
      - core
      - portal
  notary-server:
    image: goharbor/notary-server-photon:v2.1.4
    container_name: notary-server
    restart: always
    networks:
      - notary-sig
      - harbor-notary
    volumes:
      - ./common/config/notary:/etc/notary:z
      - type: bind
        source: /mnt/harbor/data/secret/notary/notary-signer-ca.crt
        target: /etc/notary/notary-signer-ca.crt
      - type: bind
        source: /mnt/harbor/data/secret/registry/root.crt
        target: /etc/notary/root.crt
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      - ./common/config/notary/server_env
    depends_on:
      - postgresql
      - notary-signer
  notary-signer:
    image: goharbor/notary-signer-photon:v2.1.4
    container_name: notary-signer
    restart: always
    networks:
      harbor-notary:
      notary-sig:
        aliases:
          - notarysigner
    volumes:
      - ./common/config/notary:/etc/notary:z
      - type: bind
        source: /mnt/harbor/data/secret/notary/notary-signer.crt
        target: /etc/notary/notary-signer.crt
      - type: bind
        source: /mnt/harbor/data/secret/notary/notary-signer.key
        target: /etc/notary/notary-signer.key
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      - ./common/config/notary/signer_env
    depends_on:
      - postgresql
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: goharbor/clair-photon:v2.1.4
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cpu_quota: 50000
    depends_on:
      - postgresql
    volumes:
      - type: bind
        source: ./common/config/clair/config.yaml
        target: /etc/clair/config.yaml
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      ./common/config/clair/clair_env
  clair-adapter:
    networks:
      - harbor-clair
    container_name: clair-adapter
    image: goharbor/clair-adapter-photon:v2.1.4
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    cpu_quota: 50000
    depends_on:
      - clair
      - redis
    volumes:
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      ./common/config/clair-adapter/env
  trivy-adapter:
    container_name: trivy-adapter
    image: goharbor/trivy-adapter-photon:v2.1.4
    restart: always
    cap_drop:
      - ALL
    depends_on:
      - redis
    networks:
      - harbor
    volumes:
      - type: bind
        source: /mnt/harbor/data/trivy-adapter/trivy
        target: /home/scanner/.cache/trivy
      - type: bind
        source: /mnt/harbor/data/trivy-adapter/reports
        target: /home/scanner/.cache/reports
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      ./common/config/trivy-adapter/env
  chartmuseum:
    container_name: chartmuseum
    image: goharbor/chartmuseum-photon:v2.1.4
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - harbor-chartmuseum
    volumes:
      - /mnt/harbor/data/chart_storage:/chart_storage:z
      - ./common/config/chartserver:/etc/chartserver:z
      - type: bind
        source: ./common/config/shared/trust-certificates
        target: /harbor_cust_cert
    env_file:
      ./common/config/chartserver/env
networks:
  harbor:
    external: false
  harbor-notary:
    external: false
  notary-sig:
    external: false
  harbor-clair:
    external: false
  harbor-chartmuseum:
    external: false
